version: "2.1"
services:
  stream-consumer:
    image: ehealthafrica/aether-stream-consumer
    build: ./stream-consumer
    stdin_open: true
    tty: true
    volumes:
     - ./stream-consumer/conf:/code/conf
    command: start
