version: "2.1"

networks:
  zeebe_network:
    driver: bridge

services:
  consumer:
    extends:
      file: docker-compose-base.yml
      service: stream-consumer
    environment:
      # consumer settings
      CONSUMER_NAME: 'STREAM'
      TENANCY_HEADER: x-oauth-realm
      # redis
      REDIS_PASSWORD: password
      REDIS_DB: 0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # kafka settings
      KAFKA_CONFIG_PATH: /code/conf/consumer/kafka.json
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      KAFKA_CONSUMER_USER: ${KAFKA_SASL_USERNAME}
      KAFKA_CONSUMER_PASSWORD: ${KAFKA_SASL_PASSWORD}
      EXPOSE_PORT: 9013

    ports:
      - 9013:9013
    networks:
      - zeebe_network


  redis:
    image: redis:alpine
    command: >
      redis-server
      --requirepass password
      --appendonly yes
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
    networks:
      - zeebe_network

  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.23.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./lib/zeebe-hazelcast-exporter-0.8.0-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./conf/application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  monitor:
    container_name: zeebe-simple-monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
